### ISSUE TITLE
Suggestion: (Optionally??) Link to other workspace colours for the current tab

### ISSUE THREAD

**Issue by the-moog** [egorovsa/vscode-folder-colorizer#5]
Might be worth seeing what you can do with these settings, synchronised to current tab, workspace folder, etc.
```yaml
    "settings": {
        "workbench.colorCustomizations": {
            "activityBar.background": "#0A4B10",
            "titleBar.activeBackground": "#0A4B10",
            "titleBar.activeForeground": "#F1FDF2",
            "activityBar.border": "#0A4B10",
            "statusBar.border": "#0A4B10",
            "tab.activeBorderTop": "#0A4B10"
        },
        "folder-color.pathColors": [
            {......
```
